"""add allowed_at to waitlist_signups

Revision ID: 4422da887db6
Revises: 87f9e6dd4ce1
Create Date: 2026-06-03 20:01:32.505802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4422da887db6'
down_revision: Union[str, Sequence[str], None] = '87f9e6dd4ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_signups', sa.Column('allowed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist_signups', 'allowed_at')
    # ### end Alembic commands ###

