"""add push notifications

Revision ID: 7005338bb031
Revises: 465041cfdecb
Create Date: 2026-07-23 23:36:36.476047

Autogenerate also proposed four unrelated changes from pre-existing model/SQLite
drift (an api_keys index uniqueness flip, a list_invites index drop, a
list_items.stores nullability change, and a receipt_scans.receipt_at type
change). All were removed: they are not part of this feature, and the last is an
artifact of SQLite reflecting the previous migration's DATE as a distinct type.

Both new columns are nullable, so existing rows are accepted with no backfill.
purchased_by stays NULL on historical purchases -- that information was never
recorded, and every such row predates any watermark.
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7005338bb031"
down_revision: str | Sequence[str] | None = "465041cfdecb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "push_tokens",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_registered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_push_tokens_token"), "push_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_push_tokens_user_id"), "push_tokens", ["user_id"], unique=False)

    op.add_column("list_members", sa.Column("last_seen_at", sa.DateTime(), nullable=True))

    # batch_alter_table so this works on SQLite too: SQLite cannot ALTER TABLE
    # ADD CONSTRAINT, and dev runs on SQLite while production runs on Postgres.
    # The constraint is named explicitly so downgrade can drop it -- an
    # autogenerated None name is undroppable.
    with op.batch_alter_table("list_items") as batch_op:
        batch_op.add_column(
            sa.Column("purchased_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_list_items_purchased_by_users", "users", ["purchased_by"], ["id"]
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("list_items") as batch_op:
        batch_op.drop_constraint("fk_list_items_purchased_by_users", type_="foreignkey")
        batch_op.drop_column("purchased_by")

    op.drop_column("list_members", "last_seen_at")

    op.drop_index(op.f("ix_push_tokens_user_id"), table_name="push_tokens")
    op.drop_index(op.f("ix_push_tokens_token"), table_name="push_tokens")
    op.drop_table("push_tokens")
