"""add receipt tables

Revision ID: d182b25f62a5
Revises: 5ecb72b18efe
Create Date: 2026-05-26 13:14:22.075320

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd182b25f62a5'
down_revision: str | Sequence[str] | None = '5ecb72b18efe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_name_mappings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receipt_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store', 'receipt_name')
    )
    op.create_table('receipt_scans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('list_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scanned_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('receipt_total', sa.Float(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_raw', sa.JSON(), nullable=True),
    sa.Column('parsed_lines', sa.JSON(), nullable=True),
    sa.Column('match_result', sa.JSON(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_scans')
    op.drop_table('receipt_name_mappings')
    # ### end Alembic commands ###
