"""add price tables and ean to list_items

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-04-07 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5f6a7b8c9d0"
down_revision: str | Sequence[str] | None = "d4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add ean column to list_items
    op.add_column(
        "list_items",
        sa.Column("ean", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    # Create price_cache table
    op.create_table(
        "price_cache",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ean", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("price_per", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_cache_ean"), "price_cache", ["ean"], unique=True)

    # Create price_records table
    op.create_table(
        "price_records",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("list_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ean", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("price_per", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("store", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_item_id"],
            ["list_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_records_list_item_id"), "price_records", ["list_item_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_records_list_item_id"), table_name="price_records")
    op.drop_table("price_records")
    op.drop_index(op.f("ix_price_cache_ean"), table_name="price_cache")
    op.drop_table("price_cache")
    op.drop_column("list_items", "ean")
    # ### end Alembic commands ###
